### ISSUE TITLE
ARM VI 

### ISSUE THREAD

**Issue by blackfa1con** [aovrn/lisa_reloader#1]
Thank you for this awesome code 
i was working in a solution like this but finally i got some thing work .

i need to compile it in VS 2005 but i got many errors ...

maybe i must use eVC 3/4 ?

also can i contact you , i  need help in some of korean head units ...

**Comment by aovrn** [comment]
I used eVC 4 fo this project.

**Comment by blackfa1con** [comment]
That's good , its work and i built it to what i need ..

but how about ( wmmhook.dll ) , can you upload it to the repo please ? 

if we get ARM version it will be good
